#! /bin/bash

#Creation de Vm

read -p "What is the name of the VM you want to create ?
		" vmname

read -p "What is the path where you want to create the Vm ?
		" vmpath

read -p "What is the path for the iso of the Vm ?
		" isopath

VBoxManage createvm --name $vmname --ostype debian_64 --register

VBoxManage modifyvm $vmname --memory 2048 --vram 128

VBoxManage createmedium disk --filename "$vmpath/$vmname.vmdk" --sizebyte 8000000000 --format vmdk --variant fixed

VBoxManage storagectl $vmname --name "SATA Controller" --add sata --controller IntelAhci

VBoxManage storageattach $vmname --storagectl "SATA Controller" --port 0 --device 0 --type hdd --medium "$vmpath/$vmname.vmdk"

VBoxManage storagectl $vmname --name "IDE Controller" --add ide --controller PIIX4

VBoxManage storageattach $vmname --storagectl "IDE Controller" --port 1 --device 0 --type dvddrive --medium "$isopath"

printf "The Vm was successfully installed.\n"
